"use client";

import { useState } from "react";
import Link from "next/link";
import PersonaAvatar from "@/components/PersonaAvatar";
import { BRIEF, PLAN_MATRIX, PLAN_STATS, TOPICS, ADVANCED, RECEIVE } from "@/lib/orchestration";

function MatrixChip({ p }: { p: (typeof PLAN_MATRIX)[number] }) {
  const initials = p.name.split(" ").map((w) => w[0]).slice(0, 2).join("");
  return (
    <span className="flex items-center gap-2.5 rounded-[10px] border border-[#E4E4E7] bg-white py-2 pl-2.5 pr-3">
      {p.slug ? (
        <PersonaAvatar slug={p.slug} size={28} />
      ) : (
        <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[#E4E4E7] text-[10px] font-bold text-[#52525B]">{initials}</span>
      )}
      <span className="flex flex-col">
        <span className="text-[12.5px] font-semibold leading-4 text-[#18181B]">{p.name}</span>
        <span className="text-[11px] font-medium leading-[14px] text-[#A1A1AA]">{p.tag}</span>
      </span>
    </span>
  );
}

export default function PlanState({ onEdit, onRun }: { onEdit: () => void; onRun: () => void }) {
  const [expanded, setExpanded] = useState(true);
  const [saved, setSaved] = useState(false);

  return (
    <div className="mx-auto flex w-full max-w-[900px] flex-col gap-4 px-8 py-7">
      {/* Brief hero */}
      <div className="flex flex-col gap-3 rounded-xl border border-[#E4E4E7] bg-white p-5">
        <p className="text-[16px] leading-6 text-[#18181B]">{BRIEF}</p>
        <div className="flex items-center gap-3 border-t border-[#F0F0F1] pt-3">
          <span className="text-[11px] font-semibold uppercase tracking-[0.06em] text-[#A1A1AA]">Plain-language brief</span>
          <span className="flex-1" />
          <button onClick={onEdit} className="text-[13px] font-semibold text-[#52525B] transition-colors hover:text-[#CC0000]">Edit brief</button>
        </div>
      </div>

      {/* Plan header */}
      <div className="flex items-center gap-2.5">
        <span className="text-[18px] font-bold leading-6 tracking-[-0.01em] text-[#18181B]">Here&apos;s my plan</span>
        <span className="flex items-center gap-1.5 rounded-full bg-[#F3EEFE] px-2.5 py-[3px] text-[11px] font-semibold text-[#7C3AED]">
          <svg width="11" height="11" viewBox="0 0 24 24"><path d="M12 3 L13.4 9.2 L19.5 10.6 L13.4 12 L12 18.5 L10.6 12 L4.5 10.6 L10.6 9.2 Z" fill="#7C3AED" /></svg>
          Generated by AI
        </span>
        <span className="text-[12.5px] text-[#A1A1AA]">You can review, not required</span>
        <span className="flex-1" />
        <button onClick={() => setExpanded((v) => !v)} className="flex h-7 w-7 items-center justify-center rounded-md hover:bg-[#F4F4F5]">
          <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
            <path d={expanded ? "M4 10 L8 6 L12 10" : "M4 6 L8 10 L12 6"} stroke="#6E6E73" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
        </button>
      </div>

      {/* Plan card */}
      <div className="flex flex-col rounded-xl border border-[#E4E4E7] bg-white">
        {/* Value band */}
        <div className="flex items-stretch border-b border-[#F0F0F1]">
          {PLAN_STATS.map((s, i) => (
            <div key={s.label} className={`flex flex-1 flex-col gap-0.5 px-5 py-4 ${i > 0 ? "border-l border-[#F0F0F1]" : ""}`}>
              <span className="text-[20px] font-bold leading-6 tracking-[-0.01em] text-[#18181B]">{s.value}</span>
              <span className="text-[12px] text-[#71717A]">{s.label}</span>
            </div>
          ))}
        </div>

        <div className="flex flex-col gap-5 p-5">
          {/* Who I'll interview */}
          <div className="flex flex-col gap-3">
            <div className="flex items-center gap-2">
              <span className="text-[14px] font-semibold text-[#18181B]">Who I&apos;ll interview</span>
              <span className="rounded-full bg-[#F4F4F5] px-2 py-0.5 text-[11px] font-bold text-[#71717A]">5</span>
            </div>
            <div className="flex flex-wrap gap-2.5">
              {PLAN_MATRIX.map((p) => <MatrixChip key={p.name} p={p} />)}
            </div>
          </div>

          {expanded && (
            <>
              {/* Topics */}
              <div className="flex flex-col gap-2.5 border-t border-[#F0F0F1] pt-5">
                <span className="text-[14px] font-semibold text-[#18181B]">Topics I&apos;ll explore</span>
                <div className="flex flex-col gap-2">
                  {TOPICS.map((t, i) => (
                    <div key={t} className="flex items-center gap-3">
                      <span className="flex h-[22px] w-[22px] shrink-0 items-center justify-center rounded-md bg-[#F4F4F5] text-[11px] font-bold text-[#52525B]">{i + 1}</span>
                      <span className="text-[13.5px] text-[#27272A]">{t}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Advanced */}
              <div className="flex flex-col gap-2.5 border-t border-[#F0F0F1] pt-5">
                <span className="text-[14px] font-semibold text-[#18181B]">Advanced</span>
                <div className="flex flex-col gap-2">
                  {ADVANCED.map((a) => (
                    <div key={a.label} className="flex items-baseline gap-3 text-[13px]">
                      <span className="w-32 shrink-0 font-medium text-[#71717A]">{a.label}</span>
                      <span className="text-[#27272A]">{a.value}</span>
                    </div>
                  ))}
                </div>
              </div>
            </>
          )}

          {/* Adapt helper */}
          <div className="flex items-start gap-2 rounded-lg bg-[#FAFAFA] px-3 py-2.5">
            <svg width="15" height="15" viewBox="0 0 16 16" fill="none" className="mt-0.5 shrink-0"><circle cx="8" cy="8" r="7" stroke="#A1A1AA" strokeWidth="1.3" /><path d="M8 7.2V11" stroke="#A1A1AA" strokeWidth="1.4" strokeLinecap="round" /><circle cx="8" cy="5" r="0.8" fill="#A1A1AA" /></svg>
            <span className="text-[12.5px] leading-[17px] text-[#71717A]">AI may adapt the plan during interviews to get the most accurate answers.</span>
          </div>
        </div>
      </div>

      {/* What you'll receive */}
      {expanded && (
        <div className="flex flex-col gap-3 rounded-xl border border-[#E4E4E7] bg-white p-5">
          <span className="text-[14px] font-semibold text-[#18181B]">What you&apos;ll receive</span>
          <div className="grid grid-cols-2 gap-3">
            {RECEIVE.map((r) => (
              <div key={r.title} className="flex items-start gap-2.5 rounded-lg border border-[#F0F0F1] p-3">
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" className="mt-0.5 shrink-0"><path d="M20 6L9 17l-5-5" stroke="#15803D" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round" /></svg>
                <span className="flex flex-col">
                  <span className="text-[13px] font-semibold text-[#18181B]">{r.title}</span>
                  <span className="text-[12px] text-[#A1A1AA]">{r.sub}</span>
                </span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Saved toast */}
      {saved && (
        <div className="flex items-center gap-[11px] rounded-xl border border-[#DCFCE7] bg-[#F0FDF4] px-4 py-3">
          <svg width="20" height="20" viewBox="0 0 20 20" fill="none" className="shrink-0">
            <circle cx="10" cy="10" r="8.2" fill="#15803D" />
            <path d="M6.3 10.2 L8.8 12.6 L13.7 7.4" stroke="#fff" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
          <span className="text-[13px] font-semibold leading-4 text-[#15803D]">Brief saved to your library</span>
          <span className="text-[13px] leading-4 text-[#3F8259]">— re-run it on fresh data or share it anytime.</span>
          <span className="flex-1" />
          <Link href="/saved" className="text-[13px] font-semibold text-[#0E0E10] hover:text-[#CC0000]">View in Saved briefs</Link>
        </div>
      )}

      {/* Footer */}
      <div className="flex items-center gap-3 rounded-xl border border-[#E4E4E7] bg-white px-5 py-4">
        {saved ? (
          <span className="flex items-center gap-1.5 rounded-[9px] border border-[#DCFCE7] bg-[#F0FDF4] px-4 py-2.5 text-[13px] font-semibold text-[#15803D]">
            <svg width="14" height="14" viewBox="0 0 16 16" fill="none"><path d="M4 8.2 L6.6 10.8 L12 5.4" stroke="#15803D" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" /></svg>
            Saved
          </span>
        ) : (
          <button onClick={() => setSaved(true)} className="rounded-[9px] border border-[#E4E4E7] px-4 py-2.5 text-[13px] font-semibold text-[#52525B] transition-colors hover:border-[#CC0000]">Save brief</button>
        )}
        <span className="text-[12.5px] text-[#A1A1AA]">You can pause or stop anytime</span>
        <span className="flex-1" />
        <button onClick={onRun} className="flex items-center gap-2 rounded-[9px] bg-[#CC0000] px-4 py-2 text-[13px] font-semibold text-white transition-colors hover:bg-[#B8041A]">
          Run research
          <svg width="15" height="15" viewBox="0 0 24 24" fill="none"><path d="M5 12h14M13 6l6 6-6 6" stroke="#FFFFFF" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" /></svg>
        </button>
      </div>
    </div>
  );
}
